Update typescript
forcedotcom/sfdx-dev-packages pull request #109
Opened 2021-01-19 20:06 UTC by mdonnalley

Updates
- typescript to `4.1.3`

@W-8667867@

2021-01-19 21:09 UTC, shetzel requested changes
Lots of great changes in this!  However, I think we can remove more rule disablements.  It should be very rare when we disable rules and there should be a reason provided when we do....unless we're planning to file more stories about removing rule disablements.

Not sure where things are with the lazy loader code.  Maybe @amphro has a better sense of the status of that lib.

2021-01-19 21:09 UTC, shetzel commented on packages/ts-types/src/narrowing/to.ts
> +    /* eslint-disable-next-line @typescript-eslint/no-unsafe-return */
Can't we just coerce the type returned by `JSON.parse()` to be `AnyJson` rather than disable the rule?

2021-01-21 16:41 UTC, peternhale approved these changes

2021-01-21 17:21 UTC, shetzel approved these changes

2021-01-22 22:15 UTC, amphro approved these changes
Ya, bummer we need to exclude so many rules. Some of these libraries are so low level that we will probably never completely remove all the exclusions. It might be nice to have comments on ones we will never change and TODOs for the ones we want to fix.

2021-01-22 22:15 UTC, amphro commented on packages/eslint-config-salesforce-typescript/package.json
>      "eslint": "^6.8.0",
Geesh, I wonder if we also need a similar story around keeping eslint up-to-date... it is never ending.

2021-01-28 04:33 UTC, amphro commented
I ran and tested this locally, as well as linked it to several projects. The new versions of kit and ts-types works great. The new dev scripts cause a lot of compilation problems in new repos but that is expected with a major bump of typescript, but that is only a dev dep.

2021-01-28 04:35 UTC, merged